version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: filament-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - filament

  # Nginx Service
  web:
    image: nginx:1.25
    container_name: filament-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - filament
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: filament-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: filament
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: filament
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - filament-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - filament

  # Valkey Service (Redis fork)
  valkey:
    image: valkey/valkey:latest
    container_name: filament-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - filament-valkey:/data
    networks:
      - filament

networks:
  filament:
    driver: bridge

volumes:
  filament-mysql:
    driver: local
  filament-valkey:
    driver: local